language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8.3
      brew_packages: gsl
      latex: false
    - os: osx
      osx_image: xcode7.3
      brew_packages: gsl
      latex: false

addons:
  apt:
    packages:
      - libgsl-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
